### ISSUE TITLE
Ganjar_1301180237_S1 Informatika_Chatbot

### ISSUE THREAD

**Issue by zarszz** [helloproclub/Milk-Tea#10]
Name: Ganjar Gingin Tahyudin
Nim: 13081180237
Major: S1 Informatika
Github Account: https://github.com/zarszz
LinkedIn Account: https://www.linkedin.com/in/ganjar-g-745693109/
Project Link: https://github.com/zarszz/healthy-for-bot

**Comment by zarszz** [comment]
oke

**Comment by blinfoldking** [comment]
Thank you for your submission, we will be sure to review your submission as soon as possible

**Comment by blinfoldking** [comment]
well, because php is not something that i use very often, could you @jeremylombogia check this one for me

**Comment by jeremyfl** [comment]
Don't tell lies @BlinfoldKing, I know you hide your lovely PHP project in private repo.

Well @zarszz, after take a look inside your repo, there is some conclusion that maybe important for you in the future: 

- Give more detail documentation in README.md, not all people know how to test it, once again take a look the resource below, if you are lazy (like me) to do it manually, just install code formatter / linter in your text editor.
- Your commit message should signify what code changes at that moment, it may help you track what you changes previously.

Overall is good, I have tried your bot, it have many complex feature 👏

Thanks for your effort.

Some resource 
- PHP styleguide / PHP the right way
- [Best practice of readable code](https://code.tutsplus.com/tutorials/top-15-best-practices-for-writing-super-readable-code--net-8118)
- [Git styleguide](https://github.com/agis/git-style-guide)
- [Good README.md example](https://gist.github.com/PurpleBooth/109311bb0361f32d87a2)
