### ISSUE TITLE
Yosep Novento Nugroho_1303180081_S1 Information Technology_Apps Mobile

### ISSUE THREAD

**Issue by ventodeco** [helloproclub/Milk-Tea#11]
Name : Yosep Novento Nugroho
Nim : 1303180081
Major : S1 Information Technology
Github Account : https://github.com/ventodeco
LinkedIn Account : https://www.linkedin.com/in/yosep-novento-nugroho-b3b519176/
Project Link : https://github.com/ventodeco/pelanggan

**Comment by blinfoldking** [comment]
Thank You for your submission, i'm sure you've got the skill in mobile development, but please include your source code to the project so we can score your technical skill properly

**Comment by setyongr** [comment]
@BlinfoldKing 
I think the source is available as `.aia` file and can be opened in http://app.thunkable.com. Like stated in README.

**Comment by blinfoldking** [comment]
@setyongr i see gonna check it out later when i score the project
