### ISSUE TITLE
Irgi Ahmad Maulana_6706180041_D3RekayasaPerangkatLunakAplikasi_MobileApps

### ISSUE THREAD

**Issue by irgiahmadm** [helloproclub/Milk-Tea#12]
Name: Irgi Ahmad Maulana
Nim: 6706180041
Major: D3RekayasaPerangkatLunakAplikasi
Github Account: https://github.com/irgiahmadm
LinkedIn Account:https://www.linkedin.com/in/irgi-ahmad-maulana-752911154/
Project Link: https://github.com/irgiahmadm/KedaikeunApp

**Comment by blinfoldking** [comment]
Please complete your readme with more information as stated in this repository description

**Comment by irgiahmadm** [comment]
i have edit the readme, check it out, thanks :)
