### ISSUE TITLE
Fajar_1301160776_S1Informatika_BackEnd

### ISSUE THREAD

**Issue by fajaralhanief** [helloproclub/Milk-Tea#14]
Name : Muhammad Fajar Al Hanief
Nim : 1301160776
Major : S1 Teknik Informatika
Github Account : https://github.com/fajaralhanief
LinkedIn Account : https://www.linkedin.com/in/fajar-alhanief-b39664176/
Project Link : https://github.com/fajaralhanief/MovieTicketing

**Comment by blinfoldking** [comment]
Thank your for your participation on Proclub Teknofest 2018

**Comment by jeremyfl** [comment]
Hi @fajaralhanief, thanks for your effort to do this project and your interest to Proclub.

After take a look inside your repo, here is some conclusions that maybe useful for you: 

- Try to learn OOP & MVC concept in the beginning, it helped you control all of your code tidy, after that try to learn framework, life would be easier.
- For better code readability, many of your code file seems not consistent in indentation, or if you are lazy like me, just install code formatter in your code editor.
- Your commit message should signify what code changes at that moment, it may help you track what you changes previously. Don't commit after you finish the project.
- Your README.md is pretty detail, but you should know the difference between title and subtitle, take a look some example below.

Maybe there's a lot homework for you, It won't be easy but it should be worth it for you in the future.

You are already in the right way to choose Proclub, with your effort to make this project I believe you are potential.

Here is some resource for you

- [OOP & MVC](https://www.youtube.com/watch?v=ZKDUFoouyBI&list=PLFIM0718LjIWvxxll-6wLXrC_16h_Bl_p)
- [Why Framework](https://www.youtube.com/watch?v=_U_4FPfPeGE)
- PHP styleguide / PHP the right way
- [Best practice of readable code](https://code.tutsplus.com/tutorials/top-15-best-practices-for-writing-super-readable-code--net-8118)
- [Git styleguide](https://github.com/agis/git-style-guide)
- [Good README.md example](https://gist.github.com/PurpleBooth/109311bb0361f32d87a2)

**Comment by BlinfoldKing** [comment]
@jeremylombogia why do you close this issue ;<
