### ISSUE TITLE
RidhoSaputra_1301184402_S1Informatika_Mobile

### ISSUE THREAD

**Issue by did0x** [helloproclub/Milk-Tea#15]
Name: Muhammad Ridho Saputra
Nim: 1301184402
Major: S1 Informatika
Github Account: https://github.com/putrash
LinkedIn Account: https://www.linkedin.com/in/putrash/
Project Link: https://gitlab.com/putrash/pilkadahub-jateng

**Comment by blinfoldking** [comment]
Thank You for your submission, but i see that you don't have any readme included please add it as soon as possible
