### ISSUE TITLE
Yazid_1301174194_S1Informatika_BackEnd

### ISSUE THREAD

**Issue by yazid99** [helloproclub/Milk-Tea#3]
Name: Yazid Rahman Arif
Nim: 1301174194
Major: S1 Informatika
Github Account: https://github.com/yazid99
LinkedIn Account: https://www.linkedin.com/in/yazid-rahman-ab1a67111/
Project Link: https://github.com/yazid99/IoT-Project

**Comment by blinfoldking** [comment]
Thanks for your submission and partaking on our recruitation program, i will review your code as soon as possible

**Comment by blinfoldking** [comment]
could you please make some demo as soon as possible, and i will change your project catrgory into web development

**Comment by blinfoldking** [comment]
and please fill your linkedin profile or include a separate CV so we know the detail of your experience

**Comment by wisn** [comment]
Thanks for your submission!

I could tell your skill judging only by reading your code but it would be great if you gives us the demo (at least video or something)
