### ISSUE TITLE
Maulana_6706184112_D3RekayasaPerangkatLunakAplikasi_CLI

### ISSUE THREAD

**Issue by maulanarasoky** [helloproclub/Milk-Tea#4]
Name : Maulana Rasoky Nasution
Nim    : 6706184112
Major : D3 Rekayasa Perangkat Lunak Aplikasi
Github Account : https://github.com/maulanarasoky
LinkedIn Account : https://www.linkedin.com/in/maulana-rasoky-559606153/
Project Link : https://github.com/maulanarasoky/Beginner

**Comment by blinfoldking** [comment]
Thanks for your submission and partaking on our recruitation program, i will review your code as soon as possible

**Comment by blinfoldking** [comment]
please __add a readme__ as stated in the description to your project repository, or your project __won't__ be __reviewed__ and __scored__ as your project doesn't fit the Repository Criteria

**Comment by wisn** [comment]
Thank you for your submission!

https://github.com/maulanarasoky/Beginner/blob/4b07fad2dd2f01543dcdbc157718ab89bec9418e/Health%20Consultation/Health%20Consultation/Health%20Consultation.cpp#L45

Be careful with your conditional logic! I have tested this kind of logic on my machine and it will always return **true**.

**Comment by blinfoldking** [comment]
also it's a best practice to not include your editor (or any editor generated ) config files to a git repositories, you could add them to your .gitignore
