### ISSUE TITLE
Reyhan_1301164700_S1Informatika_FrontEnd

### ISSUE THREAD

**Issue by reydri** [helloproclub/Milk-Tea#5]
Name : Reyhan Alkadri
Nim : 1301164700
Major : S1 Teknik Informatika
Github Account : https://github.com/reydri
LinkedIn Account : https://www.linkedin.com/in/reyhan-alkadri-391129175/
Project Link : https://github.com/reydri/shutter-stock

**Comment by wisn** [comment]
Thank you for your submission! I already seen your project and I don't think this is enough for Proclub :/

A lot of thing must be improved such as your website layout and your chosen color...

**Comment by blinfoldking** [comment]
i kinda agree with @wisn , first of all you should organize your file to ease your development, and i would like to suggest. you could use a css framework (i recommended bulma )to make you project prettier and faster to develop.

and i also want to clarify that a front end is not the same as web design, so you should implement the user interactivity to your front end application to make it complete

good luck and happy hacking

**Comment by blinfoldking** [comment]
and i don't think it would be a good idea to include your styling in the html files, please make separate css files

**Comment by reydri** [comment]
@BlinfoldKing  @wisn saya sudah sedikit memperbaiki layout dan pemilihan warna

**Comment by blinfoldking** [comment]
just as i said you should implement user interactivity to make your application complete or else your application is just a mere web design

**Comment by reydri** [comment]
Kasih contoh dong kak satu yang contoh interaktivitas itu kayak gmana?

**Comment by blinfoldking** [comment]
well because your application is all about e-commerce there should a feature that user can select an item, buy it, other functionality like login and etc. but as the handbook explained you don't have to connect it to a back end, maybe you could simulate the data

**Comment by reydri** [comment]
like onchange dropdown ? hmmm if i make login and register using dummy data and save it to array in js, is that enough kak ? hmmm ok kak i think i will use vue js for some functionality, i will do it soon before 23.59

**Comment by blinfoldking** [comment]
@reydri it would be enogh gotta hurry tho, the clock's ticking

**Comment by reydri** [comment]
@BlinfoldKing   sudah saya update kak, saya pakein vuejs, walaupun simple, dan saudah nambah interkativity seperti ada popup, dan ada state local di frontend nya untuk login dan register nya. nuhun kak
