### ISSUE TITLE
Yasri_1301180377_S1Informatika_Chatbot

### ISSUE THREAD

**Issue by yasridho** [helloproclub/Milk-Tea#6]
Name: Yasri Ridho Pahlevi
Nim: 1301180377
Major: S1 Informatika
Github Account: https://github.com/Albatrous
LinkedIn Account: https://www.linkedin.com/in/yasri-ridho-2941ba134
Project Link: https://github.com/Albatrous/RionBot

**Comment by wisn** [comment]
Thank you for your submission!

First of all, you need to specify which features that contains some bugs.
Your code seems good. I need to try the bot tho. I will be back later!

**Comment by blinfoldking** [comment]
Your code is pretty good, but there are some lines that just too long. i guess you could do some refactoring to your code. overall it's good tho, haven't check the bot, gonna do it ASAP.

**Comment by blinfoldking** [comment]
you could follow the [Python Style Guid by Google](https://github.com/google/styleguide/blob/gh-pages/pyguide.md) to improve your code readability

**Comment by yasridho** [comment]
> Thank you for your submission!
> 
> First of all, you need to specify which features that contains some bugs.
> Your code seems good. I need to try the bot tho. I will be back later!

Terima kasih sarannya, beberapa bug sudah ditulis. @wisn

**Comment by yasridho** [comment]
> Your code is pretty good, but there are some lines that just too long. i guess you could do some refactoring to your code. overall it's good tho, haven't check the bot, gonna do it ASAP.

Beberapa line yang mungkin dianggap kepanjangan sudah diperbaiki. @BlinfoldKing
