### ISSUE TITLE
TeguhAinulDarajat_7708181033_D4SistemMultimedia_BackEnd

### ISSUE THREAD

**Issue by teguhdarajat** [helloproclub/Milk-Tea#7]
Name: Teguh Ainul Darajat
Nim: 7708181033
Major: D4 Sistem Multimedia
Github Account: https://github.com/teguhdarajat
LinkedIn Account: https://www.linkedin.com/in/teguhdarajat/
Project Link: https://github.com/teguhdarajat/laportsm

**Comment by blinfoldking** [comment]
Thanks for your submission and partaking on our recruitation program, i will review your code as soon as possible

**Comment by blinfoldking** [comment]
Your code is actually pretty good eventhough you haven't tried to write it clean, i guess you could read [Google C++ Style Guide](https://google.github.io/styleguide/cppguide.html) as refrence

**Comment by blinfoldking** [comment]
i think this line is not needed considering your the status default value is false
https://github.com/teguhdarajat/aturwarung-cli/blob/f182bb7f3d4b10daf8e9002fb7445cc9a33d114d/main.cpp#L77-L79

**Comment by blinfoldking** [comment]
i see that you have .pro .pro.user file, i guess it was generated by your text editor/IDE. I think you don't need to push it, you could "hide" it from git by adding a .gitignore file

**Comment by teguhdarajat** [comment]
@BlinfoldKing Thanks for reviewing my project, I have deleted not needed line on my source code. But I have some problem to delete .pro and .pro.user file, I have create .gitignore file but the file from deleted from my repo, is there any way to delete it manually?
