### ISSUE TITLE
ZiaMuhammad_6706184114_D3RekayasaPerangkatLunakAplikasi_BackEnd

### ISSUE THREAD

**Issue by zia123123** [helloproclub/Milk-Tea#8]
Name: Zia Muhammad Najieb
Nim: 6706184114
Major: D3 Rekaya Perangkat Lunak Aplikasi
Github Account: https://github.com/zia123123
LinkedIn Account: https://www.linkedin.com/in/zia-najieb-017181175/
Project Link: https://github.com/zia123123/ghurobascr

**Comment by blinfoldking** [comment]
please complete the content of your readme following the repository criteria in this repository

**Comment by blinfoldking** [comment]
and it would be appreciated if you host/deploy your web, you could try to deploy it to heroku

**Comment by blinfoldking** [comment]
i am not really the expert of php, so could any of you @vayupranaditya @jeremylombogia @wisn review this one

**Comment by jeremyfl** [comment]
@BlinfoldKing Am I a joke to you nigga?

Hi @zia123123 Thanks for your effort to do this project and your interest to Proclub. After looking into your code here is the conclusion that maybe important to you in the future as a programmer : 

- For better code readability, in [this](https://github.com/zia123123/ghurobascr/blob/61d8e146a09fdb8721f1a9105391c94515b4b83a/app/Http/Controllers/ShareController.php#L30) code seems not consistent in indentation, or if you are lazy like me, just install code formatter in your code editor, take a look the resource link below
- Give more detail documentation in README.md, not all people know how to test it, once again take a look the resource below
- Your commit message should signify what code changes at that moment, it may help you track what you changes previously. Don't commit after you finish the project, it's GIT not shitty cPanel file manager or FTP ✌️
- At least add couple more feature to submission like this, Proclub is more than a CRUD

Overall is 👍, you're understand Laravel concept well and potential to be the next Proclub. Keep it up 😉

Some resource 
- PHP styleguide / PHP the right way
- [Best practice of readable code](https://code.tutsplus.com/tutorials/top-15-best-practices-for-writing-super-readable-code--net-8118)
- [Git styleguide](https://github.com/agis/git-style-guide)
- [Good README.md example](https://gist.github.com/PurpleBooth/109311bb0361f32d87a2)
