### ISSUE TITLE
Eko_1301174099_S1Informatika_BackEnd

### ISSUE THREAD

**Issue by ehardi19** [helloproclub/Milk-Tea#9]
Name: Eko Hardiyanto
Nim: 1301174099
Major: 1301174099
Github Account: https://github.com/ehardi19
LinkedIn Account: https://www.linkedin.com/in/ehardi19/
Project Link: https://github.com/ehardi19/go-blog

**Comment by wisn** [comment]
Thank you for your submission! Here is my first advice to you: Learn how to use environment variable. Cheers!

**Comment by blinfoldking** [comment]
@ehardi19 what a interesting major you have there

**Comment by blinfoldking** [comment]
your code is already good, but i suggest try to use a linter to keep it consistent
